<script setup lang="ts">
const { t } = useLocale()
import { buildings } from '~/data/catalog'
definePageMeta({ key: route => route.path })
const route = useRoute()
const building = buildings.find(item => item.slug === route.params.slug)
if (!building) throw createError({ statusCode: 404, message: t('建筑页面不存在') })
const media = building.media
useSeoMeta({ title: () => `${t(building.name)} | CERN Minecraft`, description: () => t('{name}的现实参考与 Minecraft 还原档案，内容待补充。', { name: t(building.name) }) })
</script>
<template>
  <div v-if="building" class="building-detail"><header class="detail-intro site-shell reveal-up"><nav class="detail-breadcrumb" :aria-label="t('面包屑')"><NuxtLink to="/">{{ t('首页') }}</NuxtLink><span>/</span><NuxtLink to="/campus">{{ t('园区还原') }}</NuxtLink><span>/</span><span>{{ t('建筑档案') }}</span></nav><p class="detail-category">{{ t('建筑还原') }}</p><h1>{{ t(building.name) }}</h1><p class="detail-lead">{{ t(building.description) }}</p><div class="detail-byline"><span>{{ t('还原状态：待补充') }}</span><span>{{ t('更新日期：待补充') }}</span></div></header>
    <section class="site-shell detail-body"><ImageCompare class="reveal-up" :subject="t(building.name)" :media="media" /><div class="detail-grid"><article class="article-copy"><nav class="article-index reveal-up" :aria-label="t('本页目录')"><a href="#overview">{{ t('建筑介绍') }}</a><a href="#reconstruction">{{ t('还原记录') }}</a><a href="#references">{{ t('参考资料') }}</a></nav><section id="overview" class="reveal-up"><h2>{{ t('建筑介绍') }}</h2><p class="body-copy">{{ t(building.description) }}</p></section><section id="reconstruction" class="reveal-up"><h2>{{ t('还原记录') }}</h2><p class="body-copy">{{ t('建造过程、空间比例与还原细节待补充。') }}</p><div class="record-placeholder"><span>{{ t('日期待补充') }}</span><p>{{ t('建造记录待补充。') }}</p></div></section><section id="references" class="reveal-up"><h2>{{ t('参考资料') }}</h2><p class="body-copy">{{ t('照片与建筑资料来自 CERN 官方页面，位置来自 MapCERN。工程图纸与 Minecraft 还原记录待补充。') }}</p><a :href="media.source" class="source-reference" target="_blank" rel="noopener noreferrer"><span>{{ t(media.title) }}<small>{{ media.credit }}</small></span><span aria-hidden="true">↗</span></a><a :href="building.source" class="source-reference" target="_blank" rel="noopener noreferrer">{{ t('建筑官方介绍') }} ↗</a><a :href="'https://maps.cern.ch/arcgis/rest/services/Batiments/GeocodeServer/findAddressCandidates?SingleLine=' + building.number + '&outSR=4326&maxLocations=1&f=json'" class="source-reference" target="_blank" rel="noopener noreferrer">{{ t('建筑坐标来源') }} · MapCERN ↗</a></section></article><aside class="archive-sidebar reveal-up" style="transition-delay: 100ms"><h2>{{ t('建筑档案') }}</h2><dl class="metadata"><div><dt>{{ t('建筑编号') }}</dt><dd>{{ building.number }}</dd></div><div><dt>{{ t('所在区域') }}</dt><dd>Meyrin · C4</dd></div><div><dt>{{ t('还原状态') }}</dt><dd>{{ t('待补充') }}</dd></div><div><dt>{{ t('建造成员') }}</dt><dd>{{ t('待补充') }}</dd></div><div><dt>{{ t('资料整理') }}</dt><dd>{{ t('待补充') }}</dd></div></dl><h3>{{ t('继续浏览') }}</h3><NuxtLink v-for="other in buildings.filter(b => b.slug !== building.slug)" :key="other.slug" :to="`/campus/${other.slug}`" class="related-building">{{ t(other.name) }} <span aria-hidden="true">→</span></NuxtLink><NuxtLink to="/campus" class="text-link mt-4">{{ t('全部建筑与导览 →') }}</NuxtLink></aside></div></section>
  </div>
</template>
