import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { setTimeout as delay } from 'node:timers/promises'
import './check-locale.mjs'

const root = path.resolve(import.meta.dirname, '..')
const baseURL = process.env.NUXT_APP_BASE_URL || '/'
const routes = ['/', '/about', '/campus', '/exhibition', '/visit', ...['a', 'b', 'c'].flatMap(letter => [`/campus/building-${letter}`, `/exhibition/exhibit-${letter}`])]
for (const route of routes) {
  const html = fs.readFileSync(path.join(root, '.output/public', route, 'index.html'), 'utf8')
  for (const [, asset] of html.matchAll(/(?:src|href)="(\/[^"]*)"/g)) {
    assert.ok(asset.startsWith(baseURL), `Asset or link outside deployment base: ${asset}`)
  }
  assert.match(html, /lang="en"/, route)
  assert.match(html, /<h1[\s>]/, route)
  assert.match(html, /coming soon|to be added|to be announced|will be added|will be announced|to follow|pending/i, route)
  assert.doesNotMatch(html, /id="(?:open-game|fire-beam|check-path)"/, route)
  assert.doesNotMatch(html, /data-view=|data-playback|class="[^"]*motion-toggle/, route)
}
console.log(`PASS: ${routes.length} prerendered English pages; content placeholders; no mini-game.`)
if (!process.argv.includes('--browser')) process.exit(0)

const origin = process.env.DEMO_URL || 'http://127.0.0.1:3000'
const target = await (await fetch('http://127.0.0.1:9222/json/new?about:blank', { method: 'PUT' })).json()
const ws = new WebSocket(target.webSocketDebuggerUrl)
await new Promise((resolve, reject) => { ws.onopen = resolve; ws.onerror = reject })
let id = 0
const pending = new Map()
const errors = []
ws.onmessage = event => {
  const message = JSON.parse(event.data)
  if (message.method === 'Runtime.exceptionThrown') errors.push(message.params.exceptionDetails.text)
  if (message.method === 'Runtime.consoleAPICalled' && ['warning', 'error'].includes(message.params.type)) {
    const text = message.params.args.map(arg => arg.value || arg.description || '').join(' ')
    if (/hydration|mismatch|error/i.test(text)) errors.push(text)
  }
  if (message.id) { const job = pending.get(message.id); pending.delete(message.id); message.error ? job.reject(new Error(message.error.message)) : job.resolve(message.result) }
}
const send = (method, params = {}) => new Promise((resolve, reject) => { pending.set(++id, { resolve, reject }); ws.send(JSON.stringify({ id, method, params })) })
async function evaluate(expression) {
  const result = await send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true })
  if (result.exceptionDetails) throw new Error(result.exceptionDetails.text)
  return result.result.value
}
async function until(expression) {
  for (let i = 0; i < 100; i++) { if (await evaluate(expression)) return; await delay(100) }
  throw new Error(`Timed out: ${expression}`)
}
async function visit(route) {
  await send('Page.navigate', { url: origin + route })
  await until(`location.pathname === ${JSON.stringify(route)} && !!document.querySelector('#__nuxt main h1')`)
  await until(`!!document.querySelector('#__nuxt').__vue_app__`)
  await until(`document.documentElement.lang === (localStorage.getItem('cern-locale') || 'en')`)
  await delay(100)
}
async function click(selector) {
  await until(`!!document.querySelector(${JSON.stringify(selector)}) && !document.querySelector(${JSON.stringify(selector)}).closest('.nav-panel-enter-active, .nav-panel-leave-active')`)
  await until(`!document.querySelector(${JSON.stringify(selector)})?.closest('#desktop-menu, #mobile-menu')?.getAnimations().some(a => a.playState === 'running')`)
  await until(`!document.querySelector(${JSON.stringify(selector)})?.closest('.mobile-submenu')?.getAnimations().some(a => a.playState === 'running')`)
  const point = await evaluate(`(() => { const el = document.querySelector(${JSON.stringify(selector)}); el.scrollIntoView({block:'center',behavior:'instant'}); const r = el.getBoundingClientRect(); return {x:r.left+r.width/2,y:r.top+r.height/2}; })()`)
  await send('Input.dispatchMouseEvent', { type: 'mousePressed', ...point, button: 'left', clickCount: 1 })
  await send('Input.dispatchMouseEvent', { type: 'mouseReleased', ...point, button: 'left', clickCount: 1 })
}
async function chooseLanguage(code, scope = '.header-language') {
  await click(scope + ' [data-language-trigger]')
  await until(`document.querySelector(${JSON.stringify(scope + ' .language-options')}) && !document.querySelector(${JSON.stringify(scope + ' .language-options')}).getAnimations().some(a => a.playState === 'running')`)
  await click(scope + ' [data-locale="' + code + '"]')
  await until(`document.querySelector(${JSON.stringify(scope + ' [data-language-trigger]')}).getAttribute('aria-expanded') === 'false'`)
}
async function checkComparison() {
  await evaluate(`document.querySelector('.comparison').scrollIntoView({block:'center',behavior:'instant'})`)
  await until(`[...document.querySelectorAll('.comparison-photo')].length === 2 && [...document.querySelectorAll('.comparison-photo')].every(img => img.complete && img.naturalWidth > 0)`)
  assert.equal(await evaluate(`(() => { const real=document.querySelector('.comparison-real'), mc=document.querySelector('.comparison-minecraft'), a=real.getBoundingClientRect(), b=mc.getBoundingClientRect(); return a.width>0 && b.width>0 && a.left<b.left && a.right>b.left && b.right>a.right && Math.abs(a.top-b.top)<1 && getComputedStyle(real).maskImage.includes('gradient') && getComputedStyle(mc).maskImage.includes('gradient') && getComputedStyle(document.querySelector('.comparison-seam')).backdropFilter.includes('blur'); })()`), true)
  assert.match(await evaluate(`document.querySelector('.comparison').textContent`), /CERN 还原实景待补充/)
  assert.equal(await evaluate(`!!document.querySelector('.comparison button, [data-view], [data-playback], .motion-toggle')`), false)
}
async function screenshot(name, full = false) {
  if (process.env.CHECK_SCREENSHOTS === '0') return
  await evaluate('document.activeElement.blur(); window.scrollTo({top:0,behavior:"instant"})')
  await delay(150)
  const shot = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: full })
  fs.mkdirSync(path.join(root, '.preview'), { recursive: true })
  fs.writeFileSync(path.join(root, '.preview', name), Buffer.from(shot.data, 'base64'))
}
async function checkMap() {
  await visit('/campus')
  await until(`!document.querySelector('[data-region="C4"]').disabled`)
  assert.equal(await evaluate(`document.querySelectorAll('[data-region]').length`), 16)
  assert.equal(await evaluate(`document.querySelectorAll('[data-region]:not(:disabled)').length`), 1)
  assert.equal(await evaluate(`!!document.querySelector('.map-detail-image')`), false)
  await click('[data-region="C4"]')
  await until(`!!document.querySelector('.map-detail-image.loaded')`)
  const settled = () => until(`!document.querySelector('.map-plane').getAnimations().some(a => a.playState === 'running')`)
  await settled()
  assert.equal(await evaluate(`document.querySelector('.map-viewport').dataset.zoom`), '4')
  assert.equal(await evaluate(`document.querySelector('.region-grid').inert`), true)
  await evaluate(`document.querySelector('.map-viewport').scrollIntoView({block:'center',behavior:'instant'})`)
  const wheelPoint = await evaluate(`(() => {const r=document.querySelector('.map-viewport').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2,scroll:scrollY}})()`)
  await send('Input.dispatchMouseEvent', { type: 'mouseWheel', x: wheelPoint.x, y: wheelPoint.y, deltaX: 0, deltaY: -120 })
  await until(`Number(document.querySelector('.map-viewport').dataset.zoom)>4`)
  assert.equal(await evaluate('scrollY'), wheelPoint.scroll, 'Plain wheel must zoom the map without scrolling the page')
  await click('.map-zoom button:last-child')
  await settled()

  assert.equal(await evaluate(`document.querySelectorAll('.building-pin').length`), 3)
  assert.equal(await evaluate(`document.querySelector('.building-pin').getBoundingClientRect().width >= 44`), true)
  for (let i = 0; i < 7; i++) await click('.map-zoom button:first-child')
  assert.equal(await evaluate(`document.querySelector('.map-viewport').dataset.zoom`), '12')
  assert.equal(await evaluate(`document.querySelector('.map-zoom button:first-child').disabled`), true)
  await settled()
  await evaluate(`document.querySelector('.map-viewport').scrollIntoView({block:'center',behavior:'instant'});document.querySelector('.map-viewport').focus({preventScroll:true})`)
  const dragStart = await evaluate(`(() => {const r=document.querySelector('.map-viewport').getBoundingClientRect();return {x:r.x+r.width*.2,y:r.y+r.height*.5}})()`)
  const beforeDrag = await evaluate(`document.querySelector('.map-plane').style.transform`)
  await send('Input.dispatchMouseEvent', { type: 'mousePressed', ...dragStart, button: 'left', clickCount: 1 })
  await send('Input.dispatchMouseEvent', { type: 'mouseMoved', x: dragStart.x + 60, y: dragStart.y + 40, button: 'left', buttons: 1 })
  await send('Input.dispatchMouseEvent', { type: 'mouseReleased', x: dragStart.x + 60, y: dragStart.y + 40, button: 'left', clickCount: 1 })
  assert.notEqual(await evaluate(`document.querySelector('.map-plane').style.transform`), beforeDrag)
  const beforePan = await evaluate(`document.querySelector('.map-plane').style.transform`)

  for (const type of ['keyDown', 'keyUp']) await send('Input.dispatchKeyEvent', { type, key: 'ArrowLeft', code: 'ArrowLeft', windowsVirtualKeyCode: 37 })
  assert.notEqual(await evaluate(`document.querySelector('.map-plane').style.transform`), beforePan)
  await click('.map-zoom button:last-child')
  await settled()
  await click('[data-place="building-b"]')
  await until(`document.querySelector('#selected-name')?.textContent === 'IdeaSquare'`)
  assert.equal(await evaluate(`document.querySelector('#place-detail').getAttribute('href')`), '/campus/building-b')
  const expectedBuildings = [
    ['building-a', '科学与创新环球馆', 'globe', 6.055590885629, 46.233822937967],
    ['building-b', 'IdeaSquare', 'ideasquare', 6.054978678054, 46.234650317849],
    ['building-c', '同步回旋加速器馆', 'synchrocyclotron', 6.052627151069, 46.233037007844],
  ]
  for (const [slug, name, photo, longitude, latitude] of expectedBuildings) {
    await click('[data-place="' + slug + '"]')
    await until("document.querySelector('#selected-name')?.textContent === '" + name + "' && !document.querySelector('.map-info-enter-active')")
    await until("document.querySelector('.building-photo img')?.complete && document.querySelector('.building-photo img').naturalWidth > 0")
    assert.equal(await evaluate("document.querySelector('.building-photo img').src.endsWith('/reference/buildings/" + photo + ".jpg')"), true)
    const expectedX = 50 + (6378137 * longitude * Math.PI / 180 - 673561.5931097161) / 800 * 25
    const expectedY = 75 + (5818263.134806459 - 6378137 * Math.log(Math.tan(Math.PI / 4 + latitude * Math.PI / 360))) / 800 * 25
    const actual = await evaluate(`(() => { const el=document.querySelector('[data-place="${slug}"]');return [parseFloat(el.style.left),parseFloat(el.style.top)] })()`)
    assert.ok(Math.abs(actual[0] - expectedX) < .0001 && Math.abs(actual[1] - expectedY) < .0001, 'Marker must use the official coordinate within the exported map extent')
  }
  await click('[data-place="building-b"]')
  await until("document.querySelector('#selected-name')?.textContent === 'IdeaSquare'")

  await click('.sidebar-eyebrow button')
  assert.equal(await evaluate(`document.activeElement.dataset.place`), 'building-b')
  await click('.map-return')
  await settled()
  assert.equal(await evaluate(`document.activeElement.dataset.region`), 'C4')
  await click('.view-switch button:last-child')
  assert.equal(await evaluate(`document.querySelectorAll('.map-alternative [data-building]').length`), 3)
  await click('.view-switch button:first-child')
  for (const width of [320, 390, 768, 1440]) {
    await send('Emulation.setDeviceMetricsOverride', { width, height: 844, deviceScaleFactor: 1, mobile: width < 760 })
    await delay(150)
    assert.equal(await evaluate(`document.documentElement.scrollWidth <= innerWidth`), true, `Map width ${width}`)
  }
  await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true })
  await send('Emulation.setTouchEmulationEnabled', { enabled: true, maxTouchPoints: 2 })
  await click('[data-region="C4"]')
  await settled()
  await evaluate(`document.querySelector('.map-viewport').scrollIntoView({block:'center',behavior:'instant'})`)
  const center = await evaluate(`(() => {const r=document.querySelector('.map-viewport').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2,scroll:scrollY}})()`)
  const touch = spread => [{ x: center.x - spread, y: center.y, id: 1 }, { x: center.x + spread, y: center.y, id: 2 }]
  await send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: touch(30) })
  await send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: touch(70) })
  await send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  assert.equal(await evaluate(`Number(document.querySelector('.map-viewport').dataset.zoom) > 4`), true, 'Pinch must zoom map')
  assert.equal(await evaluate('scrollY'), center.scroll, 'Pinch must not scroll the page')
  await send('Emulation.setTouchEmulationEnabled', { enabled: false })
  await click('.map-zoom button:last-child')
  await settled()
  await click('[data-place="building-c"]')
  await until(`document.querySelector('#selected-name')?.textContent === '同步回旋加速器馆'`)
  assert.equal(await evaluate(`(() => {const a=document.querySelector('.map-frame').getBoundingClientRect(),b=document.querySelector('.map-sidebar').getBoundingClientRect();return b.top>=a.bottom})()`), true)
  await click('.map-breadcrumb button')
  for (const locale of ['en', 'fr', 'zh-Hant', 'zh-Hans']) {
    await chooseLanguage(locale)
    await until(`document.documentElement.lang === '${locale}'`)
    assert.equal(await evaluate(`document.documentElement.scrollWidth <= innerWidth`), true, locale)
  }
  await send('Network.enable')
  await send('Network.setCacheDisabled', { cacheDisabled: true })
  await send('Network.setBlockedURLs', { urls: ['*maps/cern-c4.jpg*'] })
  await click('[data-region="C4"]')
  await until(`!!document.querySelector('.map-load button')`)
  await send('Network.setBlockedURLs', { urls: [] })
  await click('.map-load button')
  await until(`!!document.querySelector('.map-detail-image.loaded') && !document.querySelector('.map-load')`)
  await send('Network.setCacheDisabled', { cacheDisabled: false })
  await click('.map-breadcrumb button')
  await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false })
  await send('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'no-preference' }] })
  await click('[data-region="C4"]')
  await until(`document.querySelector('.map-plane').getAnimations().some(a => a.playState === 'running')`)
  await settled()
  await send('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'reduce' }] })
  assert.equal(await evaluate(`getComputedStyle(document.querySelector('.map-plane')).transitionDuration`), '0s')
  await click('[data-place="building-b"]')
  await until(`!!document.querySelector('#place-detail')`)
  await click('#place-detail')
  await until(`location.pathname === '/campus/building-b'`)
  console.log('PASS: map sectors, verified building photos and georeferenced markers, plain-wheel zoom, back button, lazy detail image, zoom limits, keyboard pan, focus restoration, mobile pinch, four languages, failed-image recovery, transitions, reduced motion and building navigation.')
}

try {
  await send('Runtime.enable'); await send('Page.enable')
  await send('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'reduce' }] })
  await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false })
  const localeReset = await send('Page.addScriptToEvaluateOnNewDocument', { source: "localStorage.removeItem('cern-locale'); Object.defineProperty(navigator, 'languages', { get: () => ['en-US'] })" })
  await visit('/')
  await send('Page.removeScriptToEvaluateOnNewDocument', { identifier: localeReset.identifier })
  assert.equal(await evaluate(`document.documentElement.lang`), 'en')
  assert.equal(await evaluate(`document.querySelector('.header-language [data-language-trigger]').dataset.language`), 'en')
  await chooseLanguage('zh-Hans')
  await until(`document.documentElement.lang === 'zh-Hans'`)
  if (process.argv.includes('--map-only')) {
    await checkMap()
    assert.deepEqual(errors, [])
  } else {
  assert.equal(await evaluate(`getComputedStyle(document.body).color`), 'rgb(248, 250, 252)')
  assert.equal(await evaluate(`document.querySelector('link[rel="icon"]').getAttribute('href')`), '/favicon.ico')
  assert.deepEqual(Buffer.from(await (await fetch(origin + '/favicon.ico')).arrayBuffer()), fs.readFileSync(path.join(root, 'public/favicon.ico')))
  assert.equal(await evaluate(`(() => { const b=document.querySelector('.carousel-next').getBoundingClientRect(), s=document.querySelector('.carousel-next svg').getBoundingClientRect(); return b.width>=76 && s.width>=36 && Math.abs(b.x+b.width/2-s.x-s.width/2)<1 && Math.abs(b.y+b.height/2-s.y-s.height/2)<1 })()`), true)
  await click('[data-nav="/campus"]')
  await until(`!!document.querySelector('#desktop-menu')`)
  await screenshot('cern-desktop-menu.png')
  await evaluate(`document.querySelector('#nav-trigger-1').focus()`)
  await send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Escape', code: 'Escape', windowsVirtualKeyCode: 27 })
  await send('Input.dispatchKeyEvent', { type: 'keyUp', key: 'Escape', code: 'Escape', windowsVirtualKeyCode: 27 })
  assert.equal(await evaluate(`document.activeElement.id`), 'nav-trigger-1')
  await until(`!document.querySelector('#desktop-menu')`)
  await checkComparison()
  await screenshot('nuxt-home.png', true)
  await screenshot('nuxt-first-screen.png')
  await click('[data-nav="/campus"]')
  await click('#desktop-menu .mega-overview')
  await until(`location.pathname === '/campus' && !!document.querySelector('.map-viewport')`)
  await checkMap()
  await until(`location.pathname === '/campus/building-b' && document.querySelector('h1')?.textContent === 'IdeaSquare'`)
  await checkComparison()
  await screenshot('nuxt-building.png', true)
  await send('Page.reload')
  await until(`document.querySelector('h1')?.textContent === 'IdeaSquare'`)
  await visit('/exhibition/exhibit-c')
  assert.equal(await evaluate(`document.querySelector('h1').textContent`), '展区 C')
  await visit('/exhibition')
  assert.match(await evaluate(`document.querySelector('#lab').textContent`), /互动内容待补充/)
  assert.equal(await evaluate(`!!document.querySelector('#open-game')`), false)
  for (const width of [1440, 768, 390, 320]) {
    await send('Emulation.setDeviceMetricsOverride', { width, height: 844, deviceScaleFactor: 1, mobile: width < 760 })
    for (const route of ['/', '/campus', '/campus/building-a', '/exhibition', '/exhibition/exhibit-a', '/about', '/visit']) {
      await visit(route)
      assert.equal(await evaluate(`document.documentElement.scrollWidth <= innerWidth`), true, `${route} at ${width}px`)
    }
    if (width === 390) {
      await visit('/')
      await checkComparison()
      assert.equal(await evaluate(`(() => { const b=document.querySelector('.carousel-next').getBoundingClientRect(),s=document.querySelector('.carousel-next svg').getBoundingClientRect(); return b.width>=44 && s.width>=24 && Math.abs(b.x+b.width/2-s.x-s.width/2)<1 && Math.abs(b.y+b.height/2-s.y-s.height/2)<1 })()`), true)
      await screenshot('nuxt-mobile.png', true)
      await click('#open-menu')
      await until(`document.querySelector('#mobile-menu').open`)
      assert.equal(await evaluate(`document.querySelector('#open-menu').getAttribute('aria-expanded')`), 'true')
      await send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Escape', code: 'Escape', windowsVirtualKeyCode: 27 })
      await send('Input.dispatchKeyEvent', { type: 'keyUp', key: 'Escape', code: 'Escape', windowsVirtualKeyCode: 27 })
      await until(`!document.querySelector('#mobile-menu').open`)
      assert.equal(await evaluate(`document.activeElement.id`), 'open-menu')
      await click('#open-menu')
      await click('#mobile-menu [data-menu="/campus"] .mobile-section-trigger')
      await click('#mobile-menu a[href="/campus"]')
      await until(`location.pathname === '/campus' && !document.querySelector('#mobile-menu').open`)
      assert.equal(await evaluate(`document.querySelector('#open-menu').getAttribute('aria-expanded')`), 'false')
    }
  }
  await visit('/campus')
  await until(`!document.querySelector('[data-region="C4"]').disabled`)
  await click('[data-region="C4"]')
  await until(`!!document.querySelector('.map-detail-image.loaded')`)
  await click('[data-place="building-c"]')
  await until(`document.querySelector('#selected-name')?.textContent === '同步回旋加速器馆'`)
  await click('.map-breadcrumb button')
  await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false })
  await send('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'no-preference' }] })
  await visit('/')
  await until(`getComputedStyle(document.querySelector('.page-transition-overlay')).visibility === 'hidden'`)
  assert.equal(await evaluate(`document.querySelectorAll('.pt-block').length > 20`), true)
  await until(`document.querySelector('.slide img').complete && document.querySelector('.slide img').naturalWidth > 0`)
  await send('Input.dispatchMouseEvent', { type: 'mouseMoved', x: 10, y: 10 })
  await until(`document.querySelector('#slide-number').textContent.includes('2 / 4')`)
  await evaluate(`document.querySelector('.carousel-next').focus()`)
  const pausedSlide = await evaluate(`document.querySelector('#slide-number').textContent`)
  await delay(6800)
  assert.equal(await evaluate(`document.querySelector('#slide-number').textContent`), pausedSlide)
  await evaluate(`document.querySelector('.header-logo').focus()`)
  await until(`document.querySelector('#slide-number').textContent !== ${JSON.stringify(pausedSlide)}`)
  await evaluate(`document.querySelector('.carousel-next').focus()`)
  const resumedSlide = await evaluate(`document.querySelector('#slide-number').textContent`)
  await click('.carousel-prev')
  await delay(600)
  await click('.carousel-next')
  await until(`document.querySelector('#slide-number').textContent === ${JSON.stringify(resumedSlide)}`)
  await delay(600)
  await evaluate(`document.querySelectorAll('.reveal-up,.mask-reveal-el').forEach(el => el.scrollIntoView({behavior:'instant'}))`)
  await evaluate(`window.scrollTo({top:0,behavior:'instant'})`)
  await delay(1000)
  await screenshot('xintinglei-motion-home.png')
  await click('[data-nav="/campus"]')
  await until(`document.querySelector('#desktop-menu')?.getAnimations().some(a => a.playState === 'running')`)
  await until(`!document.querySelector('#desktop-menu')?.getAnimations().some(a => a.playState === 'running')`)
  await click('[data-nav="/campus"]')
  await until(`document.querySelector('#desktop-menu')?.getAnimations().some(a => a.playState === 'running')`)
  assert.equal(await evaluate(`document.querySelector('#desktop-menu').inert`), true)
  await until(`!document.querySelector('#desktop-menu')`)
  await click('[data-nav="/campus"]')
  await click('#desktop-menu .mega-overview')
  await until(`getComputedStyle(document.querySelector('.page-transition-overlay')).visibility === 'visible'`)
  await until(`location.pathname === '/campus' && !!document.querySelector('#open-map')`)
  await until(`getComputedStyle(document.querySelector('.page-transition-overlay')).visibility === 'hidden'`)
  await evaluate(`document.querySelector('.building-card').scrollIntoView({block:'center',behavior:'instant'})`)
  await until(`document.querySelector('.building-card').classList.contains('in')`)
  const hoverPoint = await evaluate(`(() => { const r = document.querySelector('.building-card').getBoundingClientRect(); return {x:r.left+35,y:r.top+35} })()`)
  await send('Input.dispatchMouseEvent', { type: 'mouseMoved', ...hoverPoint })
  await until(`document.querySelector('.building-card').style.transform.includes('perspective')`)
  await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true })
  await click('#open-menu')
  await until(`document.querySelector('#mobile-menu').getAnimations().some(a => a.playState === 'running')`)
  await click('.menu-close')
  await until(`document.querySelector('#mobile-menu').open && document.querySelector('#mobile-menu').inert && document.querySelector('#mobile-menu').getAnimations().some(a => a.playState === 'running')`)
  await until(`getComputedStyle(document.querySelector('#mobile-menu')).display === 'none'`)
  assert.equal(await evaluate(`document.activeElement.id`), 'open-menu')
  await click('#open-menu')
  await click('#mobile-menu [data-menu="/campus"] .mobile-section-trigger')
  assert.equal(await evaluate(`getComputedStyle(document.querySelector('#mobile-menu')).backgroundColor`), 'rgb(8, 8, 10)')
  await screenshot('cern-menu-xintinglei-colors.png')
  await click('#mobile-menu [data-menu="/exhibition"] .mobile-section-trigger')
  await until(`document.querySelector('#mobile-panel-2').getAnimations().some(a => a.playState === 'running')`)
  await until(`!document.querySelector('#mobile-panel-2').getAnimations().some(a => a.playState === 'running')`)
  assert.equal(await evaluate(`document.querySelectorAll('#mobile-menu .mobile-section-trigger[aria-expanded=true]').length`), 1)
  await click('#mobile-menu a[href="/exhibition#lab"]')
  await until(`location.pathname === '/exhibition' && location.hash === '#lab' && !document.querySelector('#mobile-menu').open`)
  await until(`getComputedStyle(document.querySelector('.page-transition-overlay')).visibility === 'hidden'`)
  await visit('/')
  await until(`getComputedStyle(document.querySelector('.page-transition-overlay')).visibility === 'hidden'`)
  await evaluate(`(() => { const el = document.querySelector('.hero-section'); el.dispatchEvent(new TouchEvent('touchstart', {touches:[new Touch({identifier:1,target:el,clientX:300,clientY:300})]})); el.dispatchEvent(new TouchEvent('touchend', {changedTouches:[new Touch({identifier:1,target:el,clientX:100,clientY:300})]})); })()`)
  await until(`document.querySelector('#slide-number').textContent.includes('2 / 4')`)
  assert.equal((await fetch(origin + '/campus/does-not-exist')).status, 404)
  await evaluate(`document.querySelector('.exhibition-layout').scrollIntoView({behavior:'instant',block:'center'})`)
  await until(`document.querySelector('.exhibition-layout img').complete && document.querySelector('.exhibition-layout img').naturalWidth > 0`)
  await send('Emulation.setDeviceMetricsOverride', { width: 900, height: 400, deviceScaleFactor: 1, mobile: false })
  await click('[data-nav="/exhibition"]')
  await until(`document.querySelector('#desktop-menu') && !document.querySelector('#desktop-menu').getAnimations().some(a => a.playState === 'running')`)
  assert.equal(await evaluate(`document.querySelector('#desktop-menu').getBoundingClientRect().bottom <= innerHeight`), true)
  await click('[data-nav="/campus"]')
  await click('#desktop-menu .mega-overview')
  await until(`getComputedStyle(document.querySelector('.page-transition-overlay')).visibility === 'visible'`)
  await send('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'reduce' }] })
  await until(`location.pathname === '/campus' && !!document.querySelector('#open-map') && getComputedStyle(document.querySelector('.page-transition-overlay')).visibility === 'hidden'`)
  await until(`document.documentElement.classList.contains('reduced-motion')`)
  assert.equal((await fetch(origin + '/exhibition/does-not-exist')).status, 404)
  await send('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'no-preference' }] })
  await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false })
  await visit('/')
  await until(`getComputedStyle(document.querySelector('.page-transition-overlay')).visibility === 'hidden'`)
  await click('.carousel-next')
  await until(`document.querySelector('.hero-copy-enter-active h1')?.getAnimations().some(a => a.playState === 'running')`)
  await until(`!document.querySelector('.hero-copy-enter-active, .hero-copy-leave-active')`)
  await evaluate(`document.querySelector('.carousel-next').click(); document.querySelector('.carousel-next').click(); document.querySelector('.carousel-prev').click()`)
  await until(`!document.querySelector('.hero-copy-enter-active, .hero-copy-leave-active') && document.querySelector('.hero-copy h1')?.textContent.includes('沿着设施')`)
  assert.equal(await evaluate(`document.querySelectorAll('.hero-copy h1').length`), 1)
  assert.equal(await evaluate(`document.querySelector('.hero-cta').getAttribute('href')`), '/visit')
  assert.equal(await evaluate(`getComputedStyle(document.querySelector('.marquee-section')).backgroundColor`), 'rgb(0, 0, 0)')
  assert.equal(await evaluate(`getComputedStyle(document.querySelector('.main-header')).backdropFilter`), 'none')
  await click('[data-nav="/about"]')
  assert.equal(await evaluate(`getComputedStyle(document.querySelector('.main-header')).backdropFilter`), 'none')
  await click('#desktop-menu .mega-overview')
  await until(`location.pathname === '/about' && getComputedStyle(document.querySelector('.page-transition-overlay')).visibility === 'hidden' && document.querySelector('h1').closest('.reveal-up')?.getAnimations().some(a => a.playState === 'running')`)
  await until(`getComputedStyle(document.querySelector('h1').closest('.reveal-up')).opacity === '1'`)
  await visit('/visit')
  await until(`getComputedStyle(document.querySelector('.page-transition-overlay')).visibility === 'hidden' && document.querySelector('h1').closest('.reveal-up')?.getAnimations().some(a => a.playState === 'running')`)
  console.log('PASS: carousel copy choreography and rapid switching; original black banner; stable header layer; inner-page motion after curtain and on direct load.')
  await send('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'reduce' }] })
  for (const [locale, heading] of [['en', 'About'], ['fr', 'Projet'], ['zh-Hans', '关于项目'], ['zh-Hant', '關於專案']]) {
    await visit('/about')
    await chooseLanguage(locale)
    await until(`document.documentElement.lang === ${JSON.stringify(locale)} && document.querySelector('h1').textContent === ${JSON.stringify(heading)}`)
    await visit('/about')
    assert.equal(await evaluate(`document.querySelector('h1').textContent`), heading)
    for (const width of [1440, 900, 834, 390, 320]) {
      await send('Emulation.setDeviceMetricsOverride', { width, height: 844, deviceScaleFactor: 1, mobile: width < 834 })
      assert.equal(await evaluate(`document.documentElement.scrollWidth <= innerWidth`), true, locale + ' at ' + width)
      if (width >= 834) assert.equal(await evaluate(`(() => { const nav=document.querySelector('.header-nav').getBoundingClientRect(),lang=document.querySelector('.header-language').getBoundingClientRect(),brand=document.querySelector('.header-logo').getBoundingClientRect();return nav.right <= lang.left && brand.right <= nav.left; })()`), true, locale + ' header at ' + width)
      else assert.equal(await evaluate(`(() => { const menu=document.querySelector('#open-menu').getBoundingClientRect(),lang=document.querySelector('.header-language').getBoundingClientRect(),brand=document.querySelector('.header-logo').getBoundingClientRect();return menu.width>=44 && menu.right<=innerWidth && brand.right<=lang.left && lang.right<=menu.left; })()`), true, locale + ' mobile header at ' + width)
    }
  }
  await click('#open-menu')
  await chooseLanguage('en', '#mobile-menu')
  await until(`document.documentElement.lang === 'en' && document.querySelector('#menu-title').textContent === 'Explore the project'`)
  await click('.menu-close')
  await until(`!document.querySelector('#mobile-menu').open`)
  await visit('/')
  assert.equal(await evaluate(`document.querySelector('.header-language [data-language-trigger]').dataset.language`), 'en')
  await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false })
  await send('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'no-preference' }] })
  await click('.header-language [data-language-trigger]')
  await until(`document.querySelector('.header-language .language-options')?.getAnimations().some(a => a.playState === 'running')`)
  await send('Input.dispatchKeyEvent', { type:'keyDown', key:'ArrowDown', code:'ArrowDown', windowsVirtualKeyCode:40 })
  await send('Input.dispatchKeyEvent', { type:'keyUp', key:'ArrowDown', code:'ArrowDown', windowsVirtualKeyCode:40 })
  assert.equal(await evaluate(`document.activeElement.dataset.locale`), 'fr')
  await send('Input.dispatchKeyEvent', { type:'keyDown', key:'Enter', code:'Enter', windowsVirtualKeyCode:13, text:'\r' })
  await send('Input.dispatchKeyEvent', { type:'keyUp', key:'Enter', code:'Enter', windowsVirtualKeyCode:13 })
  await until(`document.documentElement.lang === 'fr'`)
  await until(`!document.querySelector('.header-language .language-options')`)
  assert.equal(await evaluate(`document.activeElement.hasAttribute('data-language-trigger')`), true)
  await click('.header-language [data-language-trigger]')
  await until(`!document.querySelector('.header-language .language-menu-enter-active')`)
  await send('Input.dispatchKeyEvent', { type:'keyDown', key:'Escape', code:'Escape', windowsVirtualKeyCode:27 })
  await send('Input.dispatchKeyEvent', { type:'keyUp', key:'Escape', code:'Escape', windowsVirtualKeyCode:27 })
  await until(`document.querySelector('.header-language .language-options')?.getAnimations().some(a => a.playState === 'running')`)
  await until(`!document.querySelector('.header-language .language-options')`)
  assert.equal(await evaluate(`document.activeElement.hasAttribute('data-language-trigger')`), true)
  await chooseLanguage('en')
  await click('.header-language [data-language-trigger]')
  await click('.hero-eyebrow')
  await until(`!document.querySelector('.header-language .language-options')`)
  assert.equal(await evaluate(`!!document.querySelector('.language-select select')`), false)
  console.log('PASS: custom language menu enter/exit animations, arrow keys, Enter, Escape, focus restoration and outside click.')
  console.log('PASS: English default; four languages; persistence; mobile language control; narrow translated navigation.')
  assert.deepEqual(errors, [])
  console.log('PASS: blended comparison, map, 4 viewports, animated desktop/mobile menus, keyboard focus, carousel autoplay/focus pause/resume/swipe, tile transitions, card tilt, reduced motion, no hydration or script errors.')
  }
} catch (error) {
  console.error('Browser errors:', errors)
  console.error('Overflow:', await evaluate(`Array.from(document.querySelectorAll('body *')).filter(e => e.getBoundingClientRect().right > innerWidth + 1).map(e => ({tag:e.tagName,cls:e.className,right:e.getBoundingClientRect().right,text:e.textContent.slice(0,60)})).slice(0,15)`))
  await screenshot('check-failure.png')
  throw error
} finally {
  ws.close()
  await fetch(`http://127.0.0.1:9222/json/close/${target.id}`)
}
